apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-web-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/m0hamedKhalidMG/Digilians_Lab6.git
    targetRevision: main
    path: apps/sample-web/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-web-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
